export default [
  // ── PUBLIC HEALTH ──────────────────────────────────────────
  {
    name: "WHO News",
    slug: "who-news",
    type: "rss",
    baseUrl: "https://www.who.int/rss-feeds/news-english.xml",
    region: "global",
    category: "public-health",
    isActive: true,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "CDC Newsroom",
    slug: "cdc-news",
    type: "rss",
    // ✅ ИСПРАВЛЕНО: старый URL возвращал пустой feed
    baseUrl: "https://tools.cdc.gov/api/v2/resources/media/132608.rss",
    region: "usa",
    category: "public-health",
    isActive: true,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "FDA News",
    slug: "fda-news",
    type: "rss",
    baseUrl:
      "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml",
    region: "usa",
    category: "regulatory",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },

  // ── OPEN ACCESS NEWS ───────────────────────────────────────
  {
    name: "STAT News",
    slug: "stat-news",
    type: "rss",
    baseUrl: "https://www.statnews.com/feed/",
    region: "usa",
    category: "news",
    isActive: true,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "ScienceDaily Medicine",
    slug: "sciencedaily-medicine",
    type: "rss",
    baseUrl: "https://www.sciencedaily.com/rss/health_medicine.xml",
    region: "global",
    category: "news",
    isActive: true,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Medical News Today",
    slug: "medical-news-today",
    type: "rss",
    baseUrl: "https://www.medicalnewstoday.com/rss/news",
    region: "global",
    category: "news",
    // ✅ ИСПРАВЛЕНО: возвращал 404 — отключён
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "NIH News",
    slug: "nih-news",
    type: "rss",
    // ✅ ИСПРАВЛЕНО: старый URL /news-events/news-releases/rss.xml возвращал 404
    baseUrl: "https://www.nih.gov/feeds/news.xml",
    region: "usa",
    category: "research",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },

  // ── OPEN ACCESS JOURNALS ───────────────────────────────────
  {
    name: "PubMed Latest",
    slug: "pubmed",
    type: "api",
    baseUrl: "https://pubmed.ncbi.nlm.nih.gov",
    region: "global",
    category: "journal",
    isActive: true,
    fetchIntervalMinutes: 60,
    // ✅ ИСПРАВЛЕНО: был config: {} → query: undefined → 0 статей
    config: {
      query: "medicine[MeSH] OR clinical trial[pt] OR drug therapy[MeSH]",
    },
    rateLimit: { requestsPerMinute: 10 },
  },
  {
    name: "PLOS Medicine",
    slug: "plos-medicine",
    type: "rss",
    baseUrl: "https://journals.plos.org/plosmedicine/feed/atom",
    region: "global",
    category: "journal",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "PLOS ONE",
    slug: "plos-one",
    type: "rss",
    baseUrl: "https://journals.plos.org/plosone/feed/atom",
    region: "global",
    category: "journal",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "eLife",
    slug: "elife",
    type: "rss",
    baseUrl: "https://elifesciences.org/rss/recent.xml",
    region: "global",
    category: "journal",
    // ✅ ИСПРАВЛЕНО: возвращал 406 (не принимает заголовки парсера) — отключён
    isActive: false,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "PeerJ",
    slug: "peerj",
    type: "rss",
    // ✅ ИСПРАВЛЕНО: убран ?section=medicine — с ним возвращал 404
    baseUrl: "https://peerj.com/articles/index.rss",
    region: "global",
    category: "journal",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Frontiers in Medicine",
    slug: "frontiers-medicine",
    type: "rss",
    baseUrl: "https://www.frontiersin.org/journals/medicine/rss",
    region: "global",
    category: "journal",
    isActive: true,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },

  // ── ОТКЛЮЧЕНЫ (isActive: false) ────────────────────────────
  {
    name: "Nature Medicine",
    slug: "nature-medicine",
    type: "rss",
    baseUrl: "https://www.nature.com/nm.rss",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Nature",
    slug: "nature",
    type: "rss",
    baseUrl: "https://www.nature.com/nature.rss",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Science Magazine",
    slug: "science",
    type: "rss",
    baseUrl: "https://www.science.org/rss/news_current.xml",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "BMJ",
    slug: "bmj",
    type: "rss",
    baseUrl: "https://www.bmj.com/rss/news.xml",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "WebMD",
    slug: "webmd",
    type: "rss",
    baseUrl: "https://rss.webmd.com/rss.aspx?rss=news",
    region: "usa",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Reuters Health",
    slug: "reuters-health",
    type: "rss",
    baseUrl: "https://feeds.reuters.com/reuters/healthNews",
    region: "global",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Healthline",
    slug: "healthline",
    type: "rss",
    baseUrl: "https://www.healthline.com/rss/news",
    region: "global",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "F1000Research",
    slug: "f1000research",
    type: "rss",
    baseUrl: "https://f1000research.com/articles/rss",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "EMA News",
    slug: "ema-news",
    type: "rss",
    baseUrl: "https://www.ema.europa.eu/en/news-events/news/rss",
    region: "europe",
    category: "regulatory",
    isActive: false,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "BMC Medicine",
    slug: "bmc-medicine",
    type: "rss",
    baseUrl:
      "https://bmcmedicine.biomedcentral.com/articles/most-recent/rss.xml",
    region: "global",
    category: "journal",
    isActive: false,
    fetchIntervalMinutes: 60,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "Medscape",
    slug: "medscape",
    type: "rss",
    baseUrl: "https://www.medscape.com/cx/rssfeeds/2678.xml",
    region: "usa",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "MedPage Today",
    slug: "medpage-today",
    type: "rss",
    baseUrl: "https://www.medpagetoday.com/rss/headlines.xml",
    region: "usa",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
  {
    name: "New Scientist Health",
    slug: "new-scientist-health",
    type: "rss",
    baseUrl: "https://www.newscientist.com/subject/health/feed/",
    region: "global",
    category: "news",
    isActive: false,
    fetchIntervalMinutes: 30,
    config: {},
    rateLimit: { requestsPerMinute: 20 },
  },
];
